[package]
name = "api-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.29.1"
api-lib = {path = "../lib"}
tracing = "0.1.37"
axum = "0.6.18"
