name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build server
        run: cargo build --release

      - name: Install Shuttle CLI
        run: cargo install cargo-shuttle

      - name: Login to Shuttle
        run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_TOKEN }}

      - name: Deploy to Shuttle
        run: cargo shuttle deploy
