name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        # How do I use workspaces settings?
        # with:
        #   workspaces:

      - run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown --no-self-update

      - run: cargo build --release

      - run: cargo install cargo-shuttle

      - run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_TOKEN }}

      - run: cargo shuttle deploy
